package net.noliaware.yumi.commun

const val BASE_URL = "https://api.noliaware.net/yumi/user/"
const val INIT = "init"
const val CONNECT = "connect"
const val SELECT_ACCOUNT = "selectAccount"
const val GET_AVAILABLE_VOUCHER_COUNT_PER_CATEGORY = "getAvailableVoucherCountPerCategory"
const val GET_AVAILABLE_VOUCHER_LIST_BY_CATEGORY = "getAvailableVoucherListByCategory"
const val GET_VOUCHER = "getVoucher"
const val GET_ACCOUNT = "getAccount"
const val GET_USED_VOUCHER_COUNT_PER_CATEGORY = "getUsedVoucherCountPerCategory"
const val GET_USED_VOUCHER_LIST_BY_CATEGORY = "getUsedVoucherListByCategory"
const val GET_ALERT_LIST = "getAlertList"
const val GET_INBOX_MESSAGE_LIST = "getInboxMessageList"
const val GET_INBOX_MESSAGE = "getInboxMessage"
const val GET_OUTBOX_MESSAGE_LIST = "getOutboxMessageList"
const val GET_OUTBOX_MESSAGE = "getOutboxMessage"
const val SEND_MESSAGE = "sendMessage"

const val LOGIN = "login"
const val APP_VERSION = "appVersion"
const val DEVICE_ID = "deviceId"
const val SESSION_ID = "sessionId"
const val SESSION_TOKEN = "sessionToken"
const val TIMESTAMP = "timestamp"
const val SALT_STRING = "saltString"
const val TOKEN = "token"
const val KEYBOARD = "keyboard"
const val ENCRYPTION_VECTOR = "encryption_vector"
const val VOUCHER_ID = "voucherId"
const val LIMIT = "limit"
const val OFFSET = "offset"
const val SUBJECT = "subject"
const val MESSAGE = "message"
const val MESSAGES = "messages"
const val ALERTS = "alerts"
const val ACCOUNT_DATA = "account_data"
const val CATEGORIES_DATA = "categories_data"
const val MANAGED_PROFILES_DATA = "managed_profiles_data"
const val CATEGORY_ID = "categoryId"

const val MESSAGE_INBOX_DAT = "message_inbox_dat"
const val MESSAGE_OUTBOX_DAT = "message_outbox_dat"

//FRAGMENT TAGS
const val ACCOUNTS_LIST_FRAGMENT_TAG = "accounts_list_fragment"
const val VOUCHERS_LIST_FRAGMENT_TAG = "vouchers_list_fragment"
const val VOUCHER_DETAILS_FRAGMENT_TAG = "voucher_details_fragment"
const val READ_MESSAGE_FRAGMENT_TAG = "read_message_fragment"
const val SEND_MESSAGES_FRAGMENT_TAG = "send_messages_fragment"

const val GOLDEN_RATIO = 1.6180339887