name: Generate AAB Release

env:
  MAIN_project_module: app

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Build app bundle release (AAB)
        run: ./gradlew app:bundleRelease

      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: Release APK - ${{ env.RELEASE_DATE }}
          path: app/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v3
        with:
          name: Release AAB - ${{ env.RELEASE_DATE }}
          path: app/build/outputs/bundle/release/
